2024-09-05 06:48:14,673 [mHTTP GET / 200 [0.05, 127.0.0.1:61446][0m
2024-09-05 06:48:17,124 [mHTTP GET /login/ 200 [0.07, 127.0.0.1:61446][0m
2024-09-05 06:48:24,551 [32mHTTP POST /login/ 302 [1.18, 127.0.0.1:61450][0m
2024-09-05 06:48:24,705 [mHTTP GET /watchlist?greeting=True 200 [0.14, 127.0.0.1:61450][0m
2024-09-05 06:49:44,272 D:\stox\stock\settings.py changed, reloading.
2024-09-05 06:49:52,409 [mHTTP GET /watchlist?greeting=True 200 [0.05, 127.0.0.1:61494][0m
2024-09-05 06:49:59,099 [mHTTP GET / 200 [0.01, 127.0.0.1:61494][0m
2024-09-05 06:50:01,490 [32mHTTP GET /login/ 302 [0.02, 127.0.0.1:61500][0m
2024-09-05 06:50:01,523 [32mHTTP GET /market 302 [0.02, 127.0.0.1:61500][0m
2024-09-05 06:50:01,556 [mHTTP GET /watchlist 200 [0.02, 127.0.0.1:61500][0m
2024-09-05 06:50:12,582 [mHTTP GET /profile 200 [0.05, 127.0.0.1:61513][0m
2024-09-05 06:50:49,011 [mHTTP GET /contact 200 [0.18, 127.0.0.1:61524][0m
2024-09-05 06:50:49,073 Not Found: /static/landingasset/img/blog/4.jpg
2024-09-05 06:50:49,073 [33mHTTP GET /static/landingasset/img/blog/4.jpg 404 [0.01, 127.0.0.1:61524][0m
2024-09-05 06:50:49,073 Not Found: /static/landingasset/img/page-info-bg.png
2024-09-05 06:50:49,078 [33mHTTP GET /static/landingasset/img/page-info-bg.png 404 [0.02, 127.0.0.1:61525][0m
2024-09-05 06:50:53,118 [mHTTP GET /performance 200 [0.07, 127.0.0.1:61528][0m
2024-09-05 06:50:55,114 [mHTTP GET /watchlist 200 [0.03, 127.0.0.1:61528][0m
2024-09-05 06:50:57,413 [mHTTP GET /performance 200 [0.02, 127.0.0.1:61528][0m
2024-09-05 06:51:01,115 [mHTTP GET /transactions 200 [0.04, 127.0.0.1:61532][0m
2024-09-05 06:51:10,544 [mHTTP GET /trade_charges 200 [0.13, 127.0.0.1:61536][0m
2024-09-05 06:51:13,386 [mHTTP GET /portfolio 200 [0.15, 127.0.0.1:61536][0m
2024-09-05 06:51:15,063 [mHTTP GET /watchlist 200 [0.02, 127.0.0.1:61536][0m
2024-09-05 06:51:39,627 [mHTTP GET /profile 200 [0.08, 127.0.0.1:61554][0m
2024-09-05 06:51:42,769 [32mHTTP GET /logout 301 [0.02, 127.0.0.1:61554][0m
2024-09-05 06:51:42,804 [32mHTTP GET /logout/ 302 [0.03, 127.0.0.1:61554][0m
2024-09-05 06:51:42,829 [mHTTP GET /login/ 200 [0.01, 127.0.0.1:61554][0m
2024-09-05 06:51:49,983 [32mHTTP POST /login/ 302 [1.03, 127.0.0.1:61559][0m
2024-09-05 06:51:50,019 [mHTTP GET /watchlist?greeting=True 200 [0.03, 127.0.0.1:61559][0m
2024-09-05 06:51:57,946 [mHTTP GET /trade_charges 200 [0.11, 127.0.0.1:61564][0m
2024-09-05 06:52:00,003 [mHTTP GET /orders 200 [0.19, 127.0.0.1:61564][0m
2024-09-05 06:52:39,788 [mHTTP GET /performance 200 [0.02, 127.0.0.1:61577][0m
2024-09-05 06:52:41,593 [mHTTP GET /transactions 200 [0.03, 127.0.0.1:61577][0m
2024-09-05 06:53:04,412 [32mHTTP GET /trade_charges 302 [0.02, 127.0.0.1:61577][0m
2024-09-05 06:53:04,437 [mHTTP GET /login/?next=/trade_charges 200 [0.01, 127.0.0.1:61577][0m
2024-09-05 06:53:14,319 [32mHTTP POST /login/?next=/trade_charges 302 [1.07, 127.0.0.1:61577][0m
2024-09-05 06:53:14,354 [mHTTP GET /watchlist?greeting=True 200 [0.03, 127.0.0.1:61577][0m
2024-09-05 06:53:46,629 D:\stox\stock\settings.py changed, reloading.
2024-09-05 06:54:00,551 [mHTTP GET / 200 [0.02, 127.0.0.1:61606][0m
2024-09-05 06:54:02,991 [mHTTP GET /login/ 200 [0.02, 127.0.0.1:61606][0m
2024-09-05 06:54:08,225 [32mHTTP GET /watchlist 302 [0.02, 127.0.0.1:61606][0m
2024-09-05 06:54:08,241 [mHTTP GET /login/?next=/watchlist 200 [0.00, 127.0.0.1:61606][0m
2024-09-05 06:54:17,922 [32mHTTP GET /admin/ 302 [0.02, 127.0.0.1:61606][0m
2024-09-05 06:54:17,963 [mHTTP GET /admin/login/?next=/admin/ 200 [0.03, 127.0.0.1:61606][0m
2024-09-05 06:54:19,635 [32mHTTP GET /watchlist 302 [0.01, 127.0.0.1:61606][0m
2024-09-05 06:54:19,649 [mHTTP GET /login/?next=/watchlist 200 [0.01, 127.0.0.1:61606][0m
2024-09-05 06:54:27,671 [32mHTTP POST /login/?next=/watchlist 302 [1.10, 127.0.0.1:61606][0m
2024-09-05 06:54:27,728 [mHTTP GET /watchlist?greeting=True 200 [0.05, 127.0.0.1:61606][0m
2024-09-05 06:54:38,436 [32mHTTP GET /admin/ 302 [0.01, 127.0.0.1:61606][0m
2024-09-05 06:54:38,443 [mHTTP GET /admin/login/?next=/admin/ 200 [0.00, 127.0.0.1:61606][0m
2024-09-05 06:54:40,814 [32mHTTP GET /watchlist 302 [0.01, 127.0.0.1:61606][0m
2024-09-05 06:54:40,827 [mHTTP GET /login/?next=/watchlist 200 [0.01, 127.0.0.1:61606][0m
2024-09-05 07:38:16,893 D:\stox\settings\admin.py changed, reloading.
2024-09-05 07:38:21,634 [32mHTTP GET /admin/ 302 [0.05, 127.0.0.1:61874][0m
2024-09-05 07:38:21,667 [mHTTP GET /admin/login/?next=/admin/ 200 [0.03, 127.0.0.1:61874][0m
2024-09-05 07:38:32,570 [32mHTTP POST /admin/login/?next=/admin/ 302 [1.06, 127.0.0.1:61874][0m
2024-09-05 07:38:32,742 [mHTTP GET /admin/ 200 [0.17, 127.0.0.1:61874][0m
2024-09-05 07:38:42,356 Internal Server Error: /admin/settings/charges/
Traceback (most recent call last):
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: settings_charges.manipulate_5_to_25

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
  File "C:\Program Files\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\admin\options.py", line 2124, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: settings_charges.manipulate_5_to_25
2024-09-05 07:38:42,770 [35;1mHTTP GET /admin/settings/charges/ 500 [0.45, 127.0.0.1:61874][0m
2024-09-05 07:38:57,261 D:\stox\stock\settings.py changed, reloading.
2024-09-05 07:39:00,513 Internal Server Error: /admin/settings/charges/
Traceback (most recent call last):
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: settings_charges.manipulate_5_to_25

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
  File "C:\Program Files\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\admin\options.py", line 2124, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: settings_charges.manipulate_5_to_25
2024-09-05 07:39:00,528 [35;1mHTTP GET /admin/settings/charges/ 500 [0.15, 127.0.0.1:61884][0m
2024-09-05 07:39:25,090 [mHTTP GET /admin/settings/charges/ 200 [0.17, 127.0.0.1:61906][0m
2024-09-05 07:39:25,144 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:61906][0m
2024-09-05 07:40:09,637 [mHTTP GET /admin/settings/charges/1/change/ 200 [0.14, 127.0.0.1:61906][0m
2024-09-05 07:40:09,691 [mHTTP GET /admin/jsi18n/ 200 [0.02, 127.0.0.1:61906][0m
2024-09-05 07:40:20,216 D:\stox\stock\settings.py changed, reloading.
2024-09-05 07:40:27,998 D:\stox\settings\admin.py changed, reloading.
2024-09-05 07:40:31,436 [mHTTP GET /admin/settings/charges/1/change/ 200 [0.14, 127.0.0.1:61925][0m
2024-09-05 07:40:31,479 Not Found: /static/admin/js/vendor/jquery/jquery.min.js
2024-09-05 07:40:31,479 [33mHTTP GET /static/admin/js/vendor/jquery/jquery.min.js 404 [0.02, 127.0.0.1:61925][0m
2024-09-05 07:40:31,485 [mHTTP GET /admin/jsi18n/ 200 [0.02, 127.0.0.1:61927][0m
2024-09-05 07:40:31,491 Not Found: /static/admin/js/vendor/xregexp/xregexp.min.js
2024-09-05 07:40:31,491 [33mHTTP GET /static/admin/js/vendor/xregexp/xregexp.min.js 404 [0.01, 127.0.0.1:61925][0m
2024-09-05 07:43:25,531 D:\stox\settings\admin.py changed, reloading.
2024-09-05 07:44:32,666 [mHTTP GET /admin/settings/charges/1/change/ 200 [0.35, 127.0.0.1:61984][0m
2024-09-05 07:44:32,731 Not Found: /static/admin/js/vendor/jquery/jquery.min.js
2024-09-05 07:44:32,731 [33mHTTP GET /static/admin/js/vendor/jquery/jquery.min.js 404 [0.02, 127.0.0.1:61985][0m
2024-09-05 07:44:32,745 Not Found: /static/admin/js/vendor/xregexp/xregexp.min.js
2024-09-05 07:44:32,747 [33mHTTP GET /static/admin/js/vendor/xregexp/xregexp.min.js 404 [0.04, 127.0.0.1:61986][0m
2024-09-05 07:44:32,747 [mHTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:61984][0m
2024-09-05 07:44:43,732 [mHTTP GET /admin/settings/charges/ 200 [0.12, 127.0.0.1:61984][0m
2024-09-05 07:44:43,781 Not Found: /static/admin/js/vendor/xregexp/xregexp.min.js
2024-09-05 07:44:43,781 [33mHTTP GET /static/admin/js/vendor/xregexp/xregexp.min.js 404 [0.02, 127.0.0.1:61985][0m
2024-09-05 07:44:43,781 Not Found: /static/admin/js/vendor/jquery/jquery.min.js
2024-09-05 07:44:43,790 [33mHTTP GET /static/admin/js/vendor/jquery/jquery.min.js 404 [0.03, 127.0.0.1:61986][0m
2024-09-05 07:44:43,795 [mHTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:61984][0m
2024-09-05 07:46:31,071 [mHTTP GET /admin/ 200 [0.04, 127.0.0.1:62003][0m
2024-09-05 07:47:11,642 [mHTTP GET /admin/app/onstockbalancehistory/ 200 [0.11, 127.0.0.1:62003][0m
2024-09-05 07:47:11,723 Not Found: /static/admin/js/vendor/jquery/jquery.min.js
2024-09-05 07:47:11,723 Not Found: /static/admin/js/vendor/xregexp/xregexp.min.js
2024-09-05 07:47:11,726 [33mHTTP GET /static/admin/js/vendor/jquery/jquery.min.js 404 [0.04, 127.0.0.1:62004][0m
2024-09-05 07:47:11,727 [33mHTTP GET /static/admin/js/vendor/xregexp/xregexp.min.js 404 [0.03, 127.0.0.1:62009][0m
2024-09-05 07:47:11,733 [mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:62003][0m
2024-09-05 07:48:06,076 [mHTTP GET /admin/ 200 [0.08, 127.0.0.1:62003][0m
2024-09-05 07:49:09,606 [mHTTP GET /admin/app/watchlist/ 200 [0.11, 127.0.0.1:62017][0m
2024-09-05 07:49:09,735 Not Found: /static/admin/js/vendor/jquery/jquery.min.js
2024-09-05 07:49:09,741 [33mHTTP GET /static/admin/js/vendor/jquery/jquery.min.js 404 [0.02, 127.0.0.1:62018][0m
2024-09-05 07:49:09,745 [mHTTP GET /admin/jsi18n/ 200 [0.03, 127.0.0.1:62017][0m
2024-09-05 07:49:09,799 Not Found: /static/admin/js/vendor/xregexp/xregexp.min.js
2024-09-05 07:49:09,799 Not Found: /static/admin/img/icon-no.svg
2024-09-05 07:49:09,799 [33mHTTP GET /static/admin/js/vendor/xregexp/xregexp.min.js 404 [0.02, 127.0.0.1:62017][0m
2024-09-05 07:49:09,799 [33mHTTP GET /static/admin/img/icon-no.svg 404 [0.02, 127.0.0.1:62018][0m
2024-09-05 07:49:09,810 Not Found: /static/admin/img/icon-yes.svg
2024-09-05 07:49:09,812 [33mHTTP GET /static/admin/img/icon-yes.svg 404 [0.03, 127.0.0.1:62019][0m
2024-09-05 07:56:40,692 D:\stox\app\orders\market.py changed, reloading.
2024-09-05 08:01:57,433 [mHTTP GET /watchlist 200 [0.16, 127.0.0.1:62140][0m
2024-09-05 08:03:17,838 [mHTTP GET /watchlist 200 [0.12, 127.0.0.1:62147][0m
2024-09-05 08:03:20,934 [mHTTP GET /profile 200 [0.03, 127.0.0.1:62147][0m
2024-09-05 08:03:24,199 [32mHTTP GET /logout/ 302 [0.04, 127.0.0.1:62147][0m
2024-09-05 08:03:24,215 [mHTTP GET /login/ 200 [0.01, 127.0.0.1:62147][0m
2024-09-05 08:03:31,561 [32mHTTP POST /login/ 302 [1.14, 127.0.0.1:62147][0m
2024-09-05 08:03:31,602 [mHTTP GET /watchlist?greeting=True 200 [0.03, 127.0.0.1:62147][0m
2024-09-05 08:03:35,755 [mHTTP GET /watchlist 200 [0.03, 127.0.0.1:62147][0m
2024-09-05 08:09:04,396 [mHTTP GET /watchlist 200 [0.15, 127.0.0.1:62173][0m
2024-09-05 08:09:08,072 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:09:08,077 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.02, 127.0.0.1:62173][0m
2024-09-05 08:09:08,080 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:09:08,080 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.01, 127.0.0.1:62174][0m
2024-09-05 08:09:29,365 [mHTTP GET /watchlist 200 [0.12, 127.0.0.1:62195][0m
2024-09-05 08:09:30,207 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:09:30,207 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.02, 127.0.0.1:62195][0m
2024-09-05 08:09:30,223 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:09:30,223 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.01, 127.0.0.1:62195][0m
2024-09-05 08:10:24,688 [mHTTP GET /watchlist 200 [0.03, 127.0.0.1:62339][0m
2024-09-05 08:10:25,489 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:10:25,496 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:10:25,496 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.03, 127.0.0.1:62339][0m
2024-09-05 08:10:25,498 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.03, 127.0.0.1:62340][0m
2024-09-05 08:10:30,581 [mHTTP GET /watchlist 200 [0.01, 127.0.0.1:62361][0m
2024-09-05 08:10:30,968 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:10:30,968 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:10:30,968 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.02, 127.0.0.1:62361][0m
2024-09-05 08:10:30,968 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.02, 127.0.0.1:62362][0m
2024-09-05 08:15:07,004 [mHTTP GET /watchlist 200 [0.15, 127.0.0.1:62555][0m
2024-09-05 08:15:07,665 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:15:07,665 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:15:07,666 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.03, 127.0.0.1:62555][0m
2024-09-05 08:15:07,667 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.02, 127.0.0.1:62556][0m
2024-09-05 08:15:12,233 [mHTTP GET /orders 200 [0.15, 127.0.0.1:62566][0m
2024-09-05 08:15:12,779 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:15:12,779 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.01, 127.0.0.1:62566][0m
2024-09-05 08:15:12,794 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:15:12,794 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.00, 127.0.0.1:62566][0m
2024-09-05 08:16:11,313 [mHTTP GET /orders 200 [0.30, 127.0.0.1:62609][0m
2024-09-05 08:16:12,294 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:16:12,294 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:16:12,308 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.02, 127.0.0.1:62609][0m
2024-09-05 08:16:12,308 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.02, 127.0.0.1:62610][0m
2024-09-05 08:16:12,909 [mHTTP GET /orders 200 [0.15, 127.0.0.1:62610][0m
2024-09-05 08:16:13,686 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:16:13,686 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:16:13,686 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.02, 127.0.0.1:62610][0m
2024-09-05 08:16:13,686 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.02, 127.0.0.1:62609][0m
2024-09-05 08:16:14,962 [32mHTTP GET /market 302 [0.03, 127.0.0.1:62609][0m
2024-09-05 08:16:15,034 [mHTTP GET /watchlist 200 [0.07, 127.0.0.1:62609][0m
2024-09-05 08:16:15,738 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:16:15,738 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:16:15,738 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.04, 127.0.0.1:62609][0m
2024-09-05 08:16:15,738 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.04, 127.0.0.1:62610][0m
2024-09-05 08:16:18,688 [mHTTP GET /search/?q=sbin 200 [0.09, 127.0.0.1:62610][0m
2024-09-05 08:29:26,615 [mHTTP GET /watchlist 200 [0.14, 127.0.0.1:63123][0m
2024-09-05 08:29:27,356 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:29:27,356 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.02, 127.0.0.1:63123][0m
2024-09-05 08:29:27,382 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:29:27,388 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.02, 127.0.0.1:63124][0m
2024-09-05 08:29:31,528 [mHTTP GET /watchlist 200 [0.03, 127.0.0.1:63130][0m
2024-09-05 08:29:31,883 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:29:31,883 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.01, 127.0.0.1:63130][0m
2024-09-05 08:29:31,900 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:29:31,900 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.00, 127.0.0.1:63130][0m
2024-09-05 08:31:13,229 [mHTTP GET /watchlist 200 [0.05, 127.0.0.1:63198][0m
2024-09-05 08:31:13,874 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:31:13,874 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:31:13,877 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.03, 127.0.0.1:63198][0m
2024-09-05 08:31:13,878 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.03, 127.0.0.1:63199][0m
2024-09-05 08:32:17,620 [mHTTP GET /watchlist 200 [0.10, 127.0.0.1:63289][0m
2024-09-05 08:32:18,291 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:32:18,295 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:32:18,295 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.02, 127.0.0.1:63289][0m
2024-09-05 08:32:18,296 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.02, 127.0.0.1:63290][0m
2024-09-05 08:33:26,733 [mHTTP GET /watchlist 200 [0.04, 127.0.0.1:63357][0m
2024-09-05 08:33:27,220 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:33:27,221 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.01, 127.0.0.1:63357][0m
2024-09-05 08:33:27,269 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:33:27,270 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.01, 127.0.0.1:63357][0m
2024-09-05 08:34:56,542 [mHTTP GET /watchlist 200 [0.09, 127.0.0.1:63421][0m
2024-09-05 08:34:57,036 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:34:57,036 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:34:57,036 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.03, 127.0.0.1:63422][0m
2024-09-05 08:34:57,036 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.04, 127.0.0.1:63421][0m
2024-09-05 08:35:54,405 [mHTTP GET /watchlist 200 [0.05, 127.0.0.1:63464][0m
2024-09-05 08:35:55,000 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:35:55,000 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:35:55,003 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.02, 127.0.0.1:63464][0m
2024-09-05 08:35:55,004 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.02, 127.0.0.1:63465][0m
2024-09-05 08:36:00,838 [mHTTP GET /search/?q=silver 200 [0.14, 127.0.0.1:63465][0m
2024-09-05 08:36:02,582 [32mHTTP POST /add_watchlist 302 [0.01, 127.0.0.1:63474][0m
2024-09-05 08:36:02,607 [mHTTP GET /watchlist 200 [0.02, 127.0.0.1:63474][0m
2024-09-05 08:36:03,025 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:36:03,025 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:36:03,025 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.02, 127.0.0.1:63475][0m
2024-09-05 08:36:03,028 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.02, 127.0.0.1:63474][0m
2024-09-05 08:36:44,140 [mHTTP GET /watchlist 200 [0.08, 127.0.0.1:63504][0m
2024-09-05 08:36:44,957 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:36:44,957 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:36:44,960 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.03, 127.0.0.1:63504][0m
2024-09-05 08:36:44,962 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.03, 127.0.0.1:63505][0m
2024-09-05 08:36:46,397 [mHTTP GET /search/?q=si 200 [0.11, 127.0.0.1:63505][0m
2024-09-05 08:36:46,633 [mHTTP GET /search/?q=sil 200 [0.12, 127.0.0.1:63505][0m
2024-09-05 08:36:47,089 [mHTTP GET /search/?q=silv 200 [0.17, 127.0.0.1:63505][0m
2024-09-05 08:36:47,296 [mHTTP GET /search/?q=silve 200 [0.10, 127.0.0.1:63505][0m
2024-09-05 08:36:47,531 [mHTTP GET /search/?q=silver 200 [0.12, 127.0.0.1:63505][0m
2024-09-05 08:36:49,359 [32mHTTP POST /add_watchlist 302 [0.12, 127.0.0.1:63505][0m
2024-09-05 08:36:49,402 [mHTTP GET /watchlist 200 [0.03, 127.0.0.1:63505][0m
2024-09-05 08:36:50,124 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:36:50,132 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.02, 127.0.0.1:63505][0m
2024-09-05 08:36:50,182 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:36:50,182 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.01, 127.0.0.1:63505][0m
2024-09-05 08:44:37,907 D:\stox\app\views.py changed, reloading.
2024-09-05 08:44:41,833 [mHTTP GET /watchlist 200 [0.07, 127.0.0.1:63853][0m
2024-09-05 08:44:42,562 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:44:42,562 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.01, 127.0.0.1:63853][0m
2024-09-05 08:44:42,628 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:44:42,630 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.01, 127.0.0.1:63853][0m
2024-09-05 08:44:45,868 [mHTTP GET /search/?q=ba 200 [0.06, 127.0.0.1:63853][0m
2024-09-05 08:44:46,045 [mHTTP GET /search/?q=ban 200 [0.03, 127.0.0.1:63853][0m
2024-09-05 08:44:46,271 [mHTTP GET /search/?q=bank 200 [0.06, 127.0.0.1:63853][0m
2024-09-05 08:44:46,446 [mHTTP GET /search/?q=bankn 200 [0.06, 127.0.0.1:63853][0m
2024-09-05 08:44:46,777 [mHTTP GET /search/?q=bankni 200 [0.13, 127.0.0.1:63853][0m
2024-09-05 08:44:54,148 [mHTTP GET /search/?q=BANKNIFTY24 200 [0.03, 127.0.0.1:63864][0m
2024-09-05 08:44:56,567 [32mHTTP POST /add_watchlist 302 [0.09, 127.0.0.1:63864][0m
2024-09-05 08:44:56,601 [mHTTP GET /watchlist 200 [0.02, 127.0.0.1:63864][0m
2024-09-05 08:44:57,071 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:44:57,071 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.01, 127.0.0.1:63864][0m
2024-09-05 08:44:57,085 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:44:57,085 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.01, 127.0.0.1:63864][0m
2024-09-05 08:46:40,919 [mHTTP GET /watchlist 200 [0.07, 127.0.0.1:63947][0m
2024-09-05 08:46:41,430 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:46:41,431 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:46:41,432 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.09, 127.0.0.1:63948][0m
2024-09-05 08:46:41,433 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.10, 127.0.0.1:63947][0m
2024-09-05 08:49:04,535 [mHTTP GET /watchlist 200 [0.14, 127.0.0.1:64040][0m
2024-09-05 08:49:05,201 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:49:05,201 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:49:05,201 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.03, 127.0.0.1:64041][0m
2024-09-05 08:49:05,208 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.04, 127.0.0.1:64040][0m
2024-09-05 08:49:09,310 [mHTTP GET /search/?q=sbin 200 [0.02, 127.0.0.1:64040][0m
2024-09-05 08:49:49,573 [mHTTP GET /watchlist 200 [0.08, 127.0.0.1:64084][0m
2024-09-05 08:49:49,983 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:49:49,983 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:49:49,983 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.02, 127.0.0.1:64084][0m
2024-09-05 08:49:49,983 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.02, 127.0.0.1:64085][0m
2024-09-05 08:49:52,839 [mHTTP GET /search/?q=silver 200 [0.06, 127.0.0.1:64085][0m
2024-09-05 08:49:54,035 [32mHTTP POST /add_watchlist 302 [0.05, 127.0.0.1:64091][0m
2024-09-05 08:49:54,078 [mHTTP GET /watchlist 200 [0.03, 127.0.0.1:64091][0m
2024-09-05 08:49:54,457 Not Found: /static/libs/feather-icons/dist/feather.min.js.map
2024-09-05 08:49:54,457 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.01, 127.0.0.1:64091][0m
2024-09-05 08:49:54,493 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map
2024-09-05 08:49:54,493 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.01, 127.0.0.1:64091][0m
2024-09-05 08:50:00,687 [mHTTP GET /admin/app/watchlist/ 200 [0.29, 127.0.0.1:64091][0m
2024-09-05 08:50:00,763 Not Found: /static/admin/js/vendor/jquery/jquery.min.js
2024-09-05 08:50:00,763 [33mHTTP GET /static/admin/js/vendor/jquery/jquery.min.js 404 [0.02, 127.0.0.1:64092][0m
2024-09-05 08:50:00,770 Not Found: /static/admin/js/vendor/xregexp/xregexp.min.js
2024-09-05 08:50:00,770 Not Found: /static/admin/img/icon-no.svg
2024-09-05 08:50:00,770 [33mHTTP GET /static/admin/js/vendor/xregexp/xregexp.min.js 404 [0.03, 127.0.0.1:64099][0m
2024-09-05 08:50:00,770 [33mHTTP GET /static/admin/img/icon-no.svg 404 [0.02, 127.0.0.1:64100][0m
2024-09-05 08:50:00,775 [mHTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:64091][0m
2024-09-05 08:50:00,799 Not Found: /static/admin/img/icon-yes.svg
2024-09-05 08:50:00,799 Not Found: /static/admin/img/icon-no.svg
2024-09-05 08:50:00,799 [33mHTTP GET /static/admin/img/icon-yes.svg 404 [0.01, 127.0.0.1:64091][0m
2024-09-05 08:50:00,799 [33mHTTP GET /static/admin/img/icon-no.svg 404 [0.01, 127.0.0.1:64100][0m
2024-09-05 17:47:56,300 [mHTTP GET / 200 [0.07, 127.0.0.1:53329][0m
2024-09-05 17:48:03,689 [mHTTP GET /login/ 200 [0.04, 127.0.0.1:53329][0m
2024-09-05 17:48:08,654 [32mHTTP GET /admin/ 302 [0.03, 127.0.0.1:53329][0m
2024-09-05 17:48:08,676 [mHTTP GET /admin/login/?next=/admin/ 200 [0.02, 127.0.0.1:53329][0m
2024-09-05 17:48:19,392 [32mHTTP POST /admin/login/?next=/admin/ 302 [0.51, 127.0.0.1:53329][0m
2024-09-05 17:48:19,544 [mHTTP GET /admin/ 200 [0.15, 127.0.0.1:53329][0m
2024-09-05 17:48:27,897 Internal Server Error: /admin/settings/mcx_market_time/
Traceback (most recent call last):
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: settings_mcx_market_time.position_close_time

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
  File "C:\Program Files\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\admin\options.py", line 2124, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: settings_mcx_market_time.position_close_time
2024-09-05 17:48:28,181 [35;1mHTTP GET /admin/settings/mcx_market_time/ 500 [0.31, 127.0.0.1:53329][0m
2024-09-05 17:48:28,311 Not Found: /favicon.ico
2024-09-05 17:48:28,311 [33mHTTP GET /favicon.ico 404 [0.01, 127.0.0.1:53329][0m
2024-09-05 17:51:23,277 [mHTTP GET /admin/settings/mcx_market_time/ 200 [0.15, 127.0.0.1:53390][0m
2024-09-05 17:51:23,315 Not Found: /static/admin/js/vendor/jquery/jquery.min.js
2024-09-05 17:51:23,315 Not Found: /static/admin/js/vendor/xregexp/xregexp.min.js
2024-09-05 17:51:23,315 [33mHTTP GET /static/admin/js/vendor/jquery/jquery.min.js 404 [0.01, 127.0.0.1:53390][0m
2024-09-05 17:51:23,317 [33mHTTP GET /static/admin/js/vendor/xregexp/xregexp.min.js 404 [0.01, 127.0.0.1:53392][0m
2024-09-05 17:51:23,321 [mHTTP GET /admin/jsi18n/ 200 [0.02, 127.0.0.1:53391][0m
2024-09-05 17:51:33,179 [mHTTP GET /admin/settings/charges/ 200 [0.06, 127.0.0.1:53391][0m
2024-09-05 17:51:33,213 Not Found: /static/admin/js/vendor/jquery/jquery.min.js
2024-09-05 17:51:33,213 Not Found: /static/admin/js/vendor/xregexp/xregexp.min.js
2024-09-05 17:51:33,214 [33mHTTP GET /static/admin/js/vendor/jquery/jquery.min.js 404 [0.01, 127.0.0.1:53392][0m
2024-09-05 17:51:33,215 [33mHTTP GET /static/admin/js/vendor/xregexp/xregexp.min.js 404 [0.01, 127.0.0.1:53390][0m
2024-09-05 17:51:33,217 [mHTTP GET /admin/jsi18n/ 200 [0.02, 127.0.0.1:53391][0m
2024-09-05 17:51:35,394 [mHTTP GET /admin/settings/charges/1/change/ 200 [0.08, 127.0.0.1:53391][0m
2024-09-05 17:51:35,429 Not Found: /static/admin/js/vendor/xregexp/xregexp.min.js
2024-09-05 17:51:35,429 Not Found: /static/admin/js/vendor/jquery/jquery.min.js
2024-09-05 17:51:35,430 [33mHTTP GET /static/admin/js/vendor/xregexp/xregexp.min.js 404 [0.01, 127.0.0.1:53392][0m
2024-09-05 17:51:35,431 [33mHTTP GET /static/admin/js/vendor/jquery/jquery.min.js 404 [0.01, 127.0.0.1:53390][0m
2024-09-05 17:51:35,433 [mHTTP GET /admin/jsi18n/ 200 [0.02, 127.0.0.1:53391][0m
2024-09-05 17:54:57,531 D:\stox\app\orders\market.py changed, reloading.
2024-09-05 17:59:03,120 D:\stox\app\models.py changed, reloading.
2024-09-05 17:59:27,844 D:\stox\app\orders\market.py changed, reloading.
2024-09-05 18:00:08,150 D:\stox\app\orders\market.py changed, reloading.
2024-09-05 18:01:40,114 D:\stox\app\orders\market.py changed, reloading.
2024-09-05 18:04:31,491 D:\stox\app\models.py changed, reloading.
2024-09-06 16:01:57,586 [mHTTP GET / 200 [0.06, 127.0.0.1:58193][0m
2024-09-06 16:02:00,732 [mHTTP GET /login/ 200 [0.05, 127.0.0.1:58193][0m
2024-09-06 16:02:15,324 [32mHTTP GET /reset_password 301 [0.01, 127.0.0.1:58193][0m
2024-09-06 16:02:15,490 [mHTTP GET /reset_password/ 200 [0.16, 127.0.0.1:58193][0m
2024-09-06 16:02:23,386 [32mHTTP POST /reset_password/ 302 [4.96, 127.0.0.1:58193][0m
2024-09-06 16:02:23,450 [mHTTP GET /password_reset/done/ 200 [0.05, 127.0.0.1:58193][0m
2024-09-06 16:58:13,772 [mHTTP GET /login/?next=/ 200 [0.02, 127.0.0.1:59207][0m
2024-09-06 16:58:14,333 Not Found: /static/libs/simplebar/dist/simplebar.min.css
2024-09-06 16:58:14,334 [33mHTTP GET /static/libs/simplebar/dist/simplebar.min.css 404 [0.02, 127.0.0.1:59207][0m
2024-09-06 16:58:14,334 Not Found: /static/css/theme.min.css
2024-09-06 16:58:14,336 [33mHTTP GET /static/css/theme.min.css 404 [0.02, 127.0.0.1:59220][0m
2024-09-06 16:58:14,388 Not Found: /static/libs/feather-icons/dist/feather.min.js
2024-09-06 16:58:14,388 Not Found: /static/libs/simplebar/dist/simplebar.min.js
2024-09-06 16:58:14,388 Not Found: /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js
2024-09-06 16:58:14,389 Not Found: /static/js/theme.min.js
2024-09-06 16:58:14,390 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js 404 [0.03, 127.0.0.1:59220][0m
2024-09-06 16:58:14,390 [33mHTTP GET /static/libs/simplebar/dist/simplebar.min.js 404 [0.02, 127.0.0.1:59222][0m
2024-09-06 16:58:14,390 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js 404 [0.03, 127.0.0.1:59207][0m
2024-09-06 16:58:14,391 [33mHTTP GET /static/js/theme.min.js 404 [0.02, 127.0.0.1:59223][0m
2024-09-06 16:58:15,172 Not Found: /static/images/brand/logo/brand.png
2024-09-06 16:58:15,172 [33mHTTP GET /static/images/brand/logo/brand.png 404 [0.01, 127.0.0.1:59223][0m
2024-09-07 05:36:30,828 D:\stox\app\models.py changed, reloading.
2024-09-07 05:37:47,794 D:\stox\app\models.py changed, reloading.
2024-09-07 05:38:00,862 D:\stox\app\models.py changed, reloading.
2024-09-07 05:38:06,370 [mHTTP GET / 200 [0.05, 127.0.0.1:54125][0m
2024-09-07 05:38:09,829 [32mHTTP GET /admin/ 302 [0.04, 127.0.0.1:54131][0m
2024-09-07 05:38:09,856 [mHTTP GET /admin/login/?next=/admin/ 200 [0.02, 127.0.0.1:54131][0m
2024-09-07 05:38:16,986 [32mHTTP POST /admin/login/?next=/admin/ 302 [0.53, 127.0.0.1:54131][0m
2024-09-07 05:38:17,087 [mHTTP GET /admin/ 200 [0.10, 127.0.0.1:54131][0m
2024-09-07 05:38:38,325 [mHTTP GET /admin/app/onstockbalancehistory/ 200 [0.10, 127.0.0.1:54142][0m
2024-09-07 05:38:38,374 Not Found: /static/admin/js/vendor/jquery/jquery.min.js
2024-09-07 05:38:38,375 [33mHTTP GET /static/admin/js/vendor/jquery/jquery.min.js 404 [0.02, 127.0.0.1:54143][0m
2024-09-07 05:38:38,376 Not Found: /static/admin/js/vendor/xregexp/xregexp.min.js
2024-09-07 05:38:38,377 [33mHTTP GET /static/admin/js/vendor/xregexp/xregexp.min.js 404 [0.02, 127.0.0.1:54148][0m
2024-09-07 05:38:38,382 [mHTTP GET /admin/jsi18n/ 200 [0.03, 127.0.0.1:54142][0m
2024-09-07 05:38:40,254 [mHTTP GET /admin/app/onstockbalancehistory/add/ 200 [0.08, 127.0.0.1:54142][0m
2024-09-07 05:38:40,297 Not Found: /static/admin/js/admin/DateTimeShortcuts.js
2024-09-07 05:38:40,297 Not Found: /static/admin/js/calendar.js
2024-09-07 05:38:40,298 [33mHTTP GET /static/admin/js/admin/DateTimeShortcuts.js 404 [0.02, 127.0.0.1:54143][0m
2024-09-07 05:38:40,298 Not Found: /static/admin/js/vendor/jquery/jquery.min.js
2024-09-07 05:38:40,299 Not Found: /static/admin/js/vendor/xregexp/xregexp.min.js
2024-09-07 05:38:40,300 [33mHTTP GET /static/admin/js/calendar.js 404 [0.02, 127.0.0.1:54142][0m
2024-09-07 05:38:40,302 [33mHTTP GET /static/admin/js/vendor/jquery/jquery.min.js 404 [0.03, 127.0.0.1:54149][0m
2024-09-07 05:38:40,302 [33mHTTP GET /static/admin/js/vendor/xregexp/xregexp.min.js 404 [0.02, 127.0.0.1:54150][0m
2024-09-07 05:38:40,305 [mHTTP GET /admin/jsi18n/ 200 [0.03, 127.0.0.1:54148][0m
2024-09-07 05:38:41,858 Internal Server Error: /admin/app/onstockbalancehistory/add/
Traceback (most recent call last):
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
  File "C:\Program Files\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\admin\options.py", line 1945, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\admin\options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\admin\options.py", line 1855, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\admin\options.py", line 1259, in save_model
    obj.save()
  File "D:\stox\app\models.py", line 414, in save
    today = timezone.now().date() - 1
TypeError: unsupported operand type(s) for -: 'datetime.date' and 'int'
2024-09-07 05:38:42,072 [35;1mHTTP POST /admin/app/onstockbalancehistory/add/ 500 [0.24, 127.0.0.1:54148][0m
2024-09-07 05:38:42,210 Not Found: /favicon.ico
2024-09-07 05:38:42,210 [33mHTTP GET /favicon.ico 404 [0.01, 127.0.0.1:54148][0m
2024-09-07 05:38:51,952 D:\stox\app\models.py changed, reloading.
2024-09-07 05:39:12,654 D:\stox\stock\settings.py changed, reloading.
2024-09-07 05:39:18,770 [32mHTTP POST /admin/app/onstockbalancehistory/add/ 302 [0.09, 127.0.0.1:54169][0m
2024-09-07 05:39:18,855 [mHTTP GET /admin/app/onstockbalancehistory/ 200 [0.08, 127.0.0.1:54169][0m
2024-09-07 05:39:18,879 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:54169][0m
2024-09-07 05:39:32,614 D:\stox\app\models.py changed, reloading.
2024-09-07 05:39:40,129 [mHTTP POST /admin/app/onstockbalancehistory/ 200 [0.12, 127.0.0.1:54184][0m
2024-09-07 05:39:41,604 [32mHTTP POST /admin/app/onstockbalancehistory/ 302 [0.03, 127.0.0.1:54184][0m
2024-09-07 05:39:41,724 [mHTTP GET /admin/app/onstockbalancehistory/ 200 [0.11, 127.0.0.1:54184][0m
2024-09-07 05:39:41,763 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:54184][0m
2024-09-07 05:39:45,411 [mHTTP GET /admin/app/onstockbalancehistory/add/ 200 [0.06, 127.0.0.1:54184][0m
2024-09-07 05:39:45,447 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:54184][0m
2024-09-07 05:39:45,506 [mHTTP GET /static/admin/js/calendar.js 200 [0.07, 127.0.0.1:54185][0m
2024-09-07 05:39:45,507 [mHTTP GET /static/admin/js/admin/DateTimeShortcuts.js 200 [0.07, 127.0.0.1:54189][0m
2024-09-07 05:39:47,107 Internal Server Error: /admin/app/onstockbalancehistory/add/
Traceback (most recent call last):
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
  File "C:\Program Files\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\admin\options.py", line 1945, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\admin\options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\admin\options.py", line 1855, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\admin\options.py", line 1259, in save_model
    obj.save()
  File "D:\stox\app\models.py", line 414, in save
    today = timezone.now().date() - 1
TypeError: unsupported operand type(s) for -: 'datetime.date' and 'int'
2024-09-07 05:39:47,120 [35;1mHTTP POST /admin/app/onstockbalancehistory/add/ 500 [0.20, 127.0.0.1:54189][0m
2024-09-07 05:40:14,096 D:\stox\app\models.py changed, reloading.
2024-09-07 05:40:34,793 D:\stox\app\models.py changed, reloading.
2024-09-07 05:40:45,813 [32mHTTP POST /admin/app/onstockbalancehistory/add/ 302 [0.10, 127.0.0.1:54237][0m
2024-09-07 05:40:45,914 [mHTTP GET /admin/app/onstockbalancehistory/ 200 [0.10, 127.0.0.1:54237][0m
2024-09-07 05:40:45,956 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:54237][0m
2024-09-07 05:46:35,172 [mHTTP GET /admin/settings/mcx_market_time/ 200 [0.24, 127.0.0.1:54331][0m
2024-09-07 05:46:35,206 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:54331][0m
2024-09-07 05:46:37,802 [mHTTP GET /admin/settings/mcx_market_time/1/change/ 200 [0.08, 127.0.0.1:54337][0m
2024-09-07 05:46:37,831 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:54337][0m
2024-09-07 05:46:48,402 [32mHTTP POST /admin/settings/mcx_market_time/1/change/ 302 [0.02, 127.0.0.1:54347][0m
2024-09-07 05:46:48,446 [mHTTP GET /admin/settings/mcx_market_time/ 200 [0.04, 127.0.0.1:54347][0m
2024-09-07 05:46:48,478 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:54347][0m
2024-09-07 05:46:52,660 [mHTTP GET /admin/settings/nse_market_time/ 200 [0.04, 127.0.0.1:54347][0m
2024-09-07 05:46:52,690 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:54347][0m
2024-09-07 05:46:54,106 [mHTTP GET /admin/settings/nse_market_time/1/change/ 200 [0.08, 127.0.0.1:54347][0m
2024-09-07 05:46:54,142 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:54347][0m
2024-09-07 05:46:57,216 [32mHTTP POST /admin/settings/nse_market_time/1/change/ 302 [0.03, 127.0.0.1:54347][0m
2024-09-07 05:46:57,269 [mHTTP GET /admin/settings/nse_market_time/ 200 [0.05, 127.0.0.1:54347][0m
2024-09-07 05:46:57,312 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:54347][0m
2024-09-07 05:47:04,990 [mHTTP GET /watchlist 200 [0.12, 127.0.0.1:54353][0m
2024-09-07 05:47:10,075 [32mHTTP POST /place_order 302 [0.14, 127.0.0.1:54356][0m
2024-09-07 05:47:10,203 [mHTTP GET /orders 200 [0.12, 127.0.0.1:54356][0m
2024-09-07 05:47:13,944 [mHTTP GET /portfolio 200 [0.05, 127.0.0.1:54356][0m
2024-09-07 05:47:43,332 [32mHTTP GET /close_position 302 [0.10, 127.0.0.1:54378][0m
2024-09-07 05:47:43,425 [mHTTP GET /admin/ 200 [0.09, 127.0.0.1:54378][0m
2024-09-07 05:47:46,928 [mHTTP GET /portfolio 200 [0.03, 127.0.0.1:54378][0m
2024-09-07 05:48:20,814 D:\stox\app\management\commands\close_positions.py changed, reloading.
2024-09-07 05:48:27,705 [mHTTP GET /admin/ 200 [0.09, 127.0.0.1:54404][0m
2024-09-07 05:48:31,250 [32mHTTP GET /close_position 302 [0.09, 127.0.0.1:54409][0m
2024-09-07 05:48:31,335 [mHTTP GET /admin/ 200 [0.08, 127.0.0.1:54409][0m
2024-09-07 05:48:58,017 D:\stox\app\management\commands\close_positions.py changed, reloading.
2024-09-07 05:49:05,483 [mHTTP GET /portfolio 200 [0.04, 127.0.0.1:54426][0m
2024-09-07 05:49:09,718 [32mHTTP POST /place_order 302 [0.07, 127.0.0.1:54431][0m
2024-09-07 05:49:09,807 [mHTTP GET /orders 200 [0.08, 127.0.0.1:54431][0m
2024-09-07 05:49:13,092 [mHTTP GET /portfolio 200 [0.02, 127.0.0.1:54431][0m
2024-09-07 05:49:59,931 [32mHTTP POST /place_order 302 [0.05, 127.0.0.1:54446][0m
2024-09-07 05:50:00,005 [mHTTP GET /orders 200 [0.07, 127.0.0.1:54446][0m
2024-09-07 05:50:03,298 [mHTTP GET /portfolio 200 [0.02, 127.0.0.1:54446][0m
2024-09-07 05:50:30,191 [32mHTTP GET /close_position 302 [0.06, 127.0.0.1:54455][0m
2024-09-07 05:50:30,262 [mHTTP GET /admin/ 200 [0.07, 127.0.0.1:54455][0m
2024-09-07 05:50:51,896 D:\stox\app\management\commands\close_positions.py changed, reloading.
2024-09-07 05:51:01,230 [mHTTP GET /portfolio 200 [0.06, 127.0.0.1:54469][0m
2024-09-07 05:51:01,892 [mHTTP GET /portfolio 200 [0.02, 127.0.0.1:54469][0m
2024-09-07 05:51:10,261 [mHTTP GET /admin/settings/nse_market_time/1/change/ 200 [0.17, 127.0.0.1:54480][0m
2024-09-07 05:51:10,292 [mHTTP GET /admin/jsi18n/ 200 [0.00, 127.0.0.1:54480][0m
2024-09-07 05:51:15,141 [32mHTTP POST /admin/settings/nse_market_time/1/change/ 302 [0.03, 127.0.0.1:54480][0m
2024-09-07 05:51:15,320 [mHTTP GET /admin/settings/nse_market_time/ 200 [0.17, 127.0.0.1:54480][0m
2024-09-07 05:51:15,356 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:54480][0m
2024-09-07 05:51:19,607 [32mHTTP GET /close_position 302 [0.04, 127.0.0.1:54483][0m
2024-09-07 05:51:19,652 [mHTTP GET /admin/ 200 [0.04, 127.0.0.1:54483][0m
2024-09-07 06:10:20,105 Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: app_transaction.wallet

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 284, in _get_response_async
    response = await sync_to_async(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
  File "C:\Program Files\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 169, in render
    with context.bind_template(self):
  File "C:\Program Files\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\context.py", line 254, in bind_template
    context = processor(self.request)
  File "D:\stox\app\context_processors.py", line 29, in custom_admin_context
    withdrawl_requests = Transaction.objects.filter(status='REQUESTED').__len__()
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: app_transaction.wallet
2024-09-07 06:10:20,346 [35;1mHTTP GET /admin/ 500 [0.32, 127.0.0.1:54773][0m
2024-09-07 06:10:20,473 Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: app_transaction.wallet

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 284, in _get_response_async
    response = await sync_to_async(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
  File "C:\Program Files\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 169, in render
    with context.bind_template(self):
  File "C:\Program Files\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\context.py", line 254, in bind_template
    context = processor(self.request)
  File "D:\stox\app\context_processors.py", line 29, in custom_admin_context
    withdrawl_requests = Transaction.objects.filter(status='REQUESTED').__len__()
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: app_transaction.wallet
2024-09-07 06:10:20,544 [35;1mHTTP GET /admin/ 500 [0.09, 127.0.0.1:54773][0m
2024-09-07 06:10:27,799 D:\stox\stock\settings.py changed, reloading.
2024-09-07 06:10:30,358 Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: app_transaction.wallet

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 284, in _get_response_async
    response = await sync_to_async(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
  File "C:\Program Files\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 169, in render
    with context.bind_template(self):
  File "C:\Program Files\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\context.py", line 254, in bind_template
    context = processor(self.request)
  File "D:\stox\app\context_processors.py", line 29, in custom_admin_context
    withdrawl_requests = Transaction.objects.filter(status='REQUESTED').__len__()
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: app_transaction.wallet
2024-09-07 06:10:30,377 [35;1mHTTP GET /admin/ 500 [0.15, 127.0.0.1:54784][0m
2024-09-07 06:10:59,532 [mHTTP GET /admin/ 200 [0.10, 127.0.0.1:54824][0m
2024-09-07 06:11:07,016 [mHTTP GET /admin/app/transaction/ 200 [0.09, 127.0.0.1:54828][0m
2024-09-07 06:11:07,054 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:54828][0m
2024-09-07 06:11:12,286 [mHTTP GET /admin/app/transaction/add/ 200 [0.10, 127.0.0.1:54834][0m
2024-09-07 06:11:12,323 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:54834][0m
2024-09-07 06:11:16,228 [mHTTP GET /admin/app/customuser/1/change/?_to_field=id 200 [0.13, 127.0.0.1:54837][0m
2024-09-07 06:11:16,262 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:54837][0m
2024-09-07 06:11:16,327 [mHTTP GET /static/admin/js/SelectBox.js 200 [0.07, 127.0.0.1:54838][0m
2024-09-07 06:11:16,328 [mHTTP GET /static/admin/js/SelectFilter2.js 200 [0.07, 127.0.0.1:54840][0m
2024-09-07 06:11:29,027 [mHTTP GET /admin/app/transaction/add/ 200 [0.07, 127.0.0.1:54842][0m
2024-09-07 06:11:55,392 [32mHTTP POST /admin/app/transaction/add/ 302 [0.03, 127.0.0.1:54847][0m
2024-09-07 06:11:55,460 [mHTTP GET /admin/app/transaction/ 200 [0.06, 127.0.0.1:54847][0m
2024-09-07 06:11:55,499 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:54847][0m
2024-09-07 06:11:57,564 [mHTTP GET /admin/app/transaction/9/change/ 200 [0.05, 127.0.0.1:54847][0m
2024-09-07 06:11:57,593 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:54847][0m
2024-09-07 06:12:14,154 [mHTTP GET /admin/app/transaction/ 200 [0.06, 127.0.0.1:54851][0m
2024-09-07 06:12:16,279 [mHTTP GET /admin/app/transaction/add/ 200 [0.06, 127.0.0.1:54851][0m
2024-09-07 06:12:16,310 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:54851][0m
2024-09-07 06:12:18,820 [mHTTP GET /static/jazzmin/img/calendar-icons.svg 200 [0.02, 127.0.0.1:54851][0m
2024-09-07 06:12:31,972 [32mHTTP POST /admin/app/transaction/add/ 302 [0.03, 127.0.0.1:54854][0m
2024-09-07 06:12:32,034 [mHTTP GET /admin/app/transaction/ 200 [0.06, 127.0.0.1:54854][0m
2024-09-07 06:12:32,062 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:54854][0m
2024-09-07 06:12:33,774 [mHTTP GET /admin/app/transaction/10/change/ 200 [0.05, 127.0.0.1:54854][0m
2024-09-07 06:12:33,810 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:54854][0m
2024-09-07 06:14:05,593 D:\stox\app\admin.py changed, reloading.
2024-09-07 06:14:09,063 [mHTTP GET /admin/app/transaction/10/change/ 200 [0.13, 127.0.0.1:54885][0m
2024-09-07 06:14:09,092 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:54885][0m
2024-09-07 06:14:10,606 [mHTTP GET /admin/app/transaction/10/change/ 200 [0.05, 127.0.0.1:54885][0m
2024-09-07 06:14:10,639 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:54885][0m
2024-09-07 06:14:25,189 D:\stox\stock\settings.py changed, reloading.
2024-09-09 05:28:56,419 [mHTTP GET / 200 [0.07, 127.0.0.1:57363][0m
2024-09-09 05:28:56,759 Not Found: /static/images/brand/logo/brand.png
2024-09-09 05:28:56,759 [33mHTTP GET /static/images/brand/logo/brand.png 404 [0.01, 127.0.0.1:57363][0m
2024-09-09 05:29:14,117 D:\stox\stock\settings.py changed, reloading.
2024-09-09 05:29:18,639 [32mHTTP GET /admin/ 302 [0.06, 127.0.0.1:57376][0m
2024-09-09 05:29:18,689 [mHTTP GET /admin/login/?next=/admin/ 200 [0.05, 127.0.0.1:57376][0m
2024-09-09 05:29:18,826 [mHTTP GET /static/images/brand/logo/brand.png 200 [0.08, 127.0.0.1:57376][0m
2024-09-09 05:29:27,212 [32mHTTP POST /admin/login/?next=/admin/ 302 [1.15, 127.0.0.1:57376][0m
2024-09-09 05:29:27,436 [mHTTP GET /admin/ 200 [0.22, 127.0.0.1:57376][0m
2024-09-09 05:29:32,749 [32mHTTP GET /login/ 302 [0.02, 127.0.0.1:57376][0m
2024-09-09 05:29:32,772 [32mHTTP GET /market 302 [0.02, 127.0.0.1:57376][0m
2024-09-09 05:29:32,861 [mHTTP GET /watchlist 200 [0.08, 127.0.0.1:57376][0m
2024-09-09 05:29:37,452 [mHTTP GET /transactions 200 [0.03, 127.0.0.1:57376][0m
2024-09-09 05:29:48,402 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.11, 127.0.0.1:57378][0m
2024-09-09 05:29:48,402 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.11, 127.0.0.1:57376][0m
2024-09-09 05:33:02,794 [mHTTP GET /transactions 200 [0.05, 127.0.0.1:57439][0m
2024-09-09 05:35:01,544 [mHTTP GET /transactions 200 [0.06, 127.0.0.1:58373][0m
2024-09-09 05:35:05,963 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.01, 127.0.0.1:58373][0m
2024-09-09 05:35:05,968 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.02, 127.0.0.1:58374][0m
2024-09-09 05:35:28,088 [mHTTP GET /transactions 200 [0.05, 127.0.0.1:58390][0m
2024-09-09 05:35:29,005 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.03, 127.0.0.1:58390][0m
2024-09-09 05:35:29,005 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.03, 127.0.0.1:58391][0m
2024-09-09 05:35:36,568 [mHTTP GET /transactions 200 [0.05, 127.0.0.1:58414][0m
2024-09-09 05:35:37,538 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.02, 127.0.0.1:58418][0m
2024-09-09 05:35:37,752 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.03, 127.0.0.1:58418][0m
2024-09-09 05:47:32,256 D:\stox\app\models.py changed, reloading.
2024-09-09 05:47:54,924 D:\stox\app\views.py changed, reloading.
2024-09-09 05:48:22,230 D:\stox\app\views.py changed, reloading.
2024-09-09 05:49:45,712 D:\stox\app\views.py changed, reloading.
2024-09-09 05:50:21,021 D:\stox\app\urls.py changed, reloading.
2024-09-09 05:53:26,487 Internal Server Error: /transactions
Traceback (most recent call last):
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: app_transaction.checksum

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
  File "C:\Program Files\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\stox\app\views.py", line 474, in transactions
    return render(request,'dashboard/transactions.html',context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\defaulttags.py", line 325, in render
    if match:
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 414, in __bool__
    self._fetch_all()
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: app_transaction.checksum
2024-09-09 05:53:26,506 [35;1mHTTP GET /transactions 500 [0.59, 127.0.0.1:59363][0m
2024-09-09 05:53:26,964 Not Found: /favicon.ico
2024-09-09 05:53:26,964 [33mHTTP GET /favicon.ico 404 [0.02, 127.0.0.1:59363][0m
2024-09-09 05:55:24,995 [mHTTP GET /transactions 200 [0.05, 127.0.0.1:59437][0m
2024-09-09 05:57:00,341 [mHTTP GET /transactions 200 [0.05, 127.0.0.1:59471][0m
2024-09-09 05:57:12,085 [mHTTP GET /transactions 200 [0.06, 127.0.0.1:59477][0m
2024-09-09 05:57:22,465 [mHTTP GET /transactions 200 [0.05, 127.0.0.1:59480][0m
2024-09-09 05:58:01,635 [mHTTP GET /transactions 200 [0.05, 127.0.0.1:59511][0m
2024-09-09 05:58:27,965 [mHTTP GET /transactions 200 [0.04, 127.0.0.1:59518][0m
2024-09-09 06:00:20,555 [mHTTP GET /transactions 200 [0.05, 127.0.0.1:59533][0m
2024-09-09 06:00:31,202 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.03, 127.0.0.1:59534][0m
2024-09-09 06:00:31,205 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.03, 127.0.0.1:59533][0m
2024-09-09 06:04:45,457 [mHTTP GET /transactions 200 [0.04, 127.0.0.1:59808][0m
2024-09-09 06:04:47,064 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.02, 127.0.0.1:59808][0m
2024-09-09 06:04:47,067 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.02, 127.0.0.1:59809][0m
2024-09-09 06:08:00,724 [mHTTP GET /transactions 200 [0.11, 127.0.0.1:60145][0m
2024-09-09 06:08:01,254 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.01, 127.0.0.1:60146][0m
2024-09-09 06:08:01,257 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.02, 127.0.0.1:60145][0m
2024-09-09 06:08:16,645 [mHTTP GET /transactions 200 [0.05, 127.0.0.1:60145][0m
2024-09-09 06:08:17,124 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.02, 127.0.0.1:60145][0m
2024-09-09 06:08:17,131 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.03, 127.0.0.1:60146][0m
2024-09-09 06:08:36,529 Forbidden (CSRF token missing.): /add-funds
2024-09-09 06:08:36,534 [31;1mHTTP POST /add-funds 403 [0.05, 127.0.0.1:60146][0m
2024-09-09 06:08:54,592 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.03, 127.0.0.1:60146][0m
2024-09-09 06:08:54,592 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.03, 127.0.0.1:60145][0m
2024-09-09 06:08:54,632 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.02, 127.0.0.1:60145][0m
2024-09-09 06:08:54,634 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.03, 127.0.0.1:60146][0m
2024-09-09 06:08:54,654 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.01, 127.0.0.1:60146][0m
2024-09-09 06:08:54,654 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.02, 127.0.0.1:60145][0m
2024-09-09 06:08:55,056 [mHTTP GET /transactions 200 [0.03, 127.0.0.1:60146][0m
2024-09-09 06:08:56,031 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.03, 127.0.0.1:60146][0m
2024-09-09 06:08:56,033 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.03, 127.0.0.1:60145][0m
2024-09-09 06:08:57,008 Internal Server Error: /add-funds
Traceback (most recent call last):
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
  File "C:\Program Files\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\stox\app\views.py", line 507, in addFunds
    return render(request,"pay.html",{"data":data})
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: pay.html
2024-09-09 06:08:57,024 [35;1mHTTP POST /add-funds 500 [0.28, 127.0.0.1:60145][0m
2024-09-09 06:11:44,220 [mHTTP POST /add-funds 200 [0.07, 127.0.0.1:60239][0m
2024-09-09 06:11:52,153 [mHTTP POST /add-funds 200 [0.02, 127.0.0.1:60239][0m
2024-09-09 06:12:06,398 [mHTTP GET /transactions 200 [0.03, 127.0.0.1:60239][0m
2024-09-09 06:12:07,796 [mHTTP POST /add-funds 200 [0.06, 127.0.0.1:60239][0m
2024-09-09 06:12:32,303 [mHTTP GET /transactions 200 [0.04, 127.0.0.1:60239][0m
2024-09-09 06:12:33,907 [mHTTP POST /add-funds 200 [0.06, 127.0.0.1:60239][0m
2024-09-09 06:13:27,635 [mHTTP POST /add-funds 200 [0.06, 127.0.0.1:60239][0m
2024-09-09 06:13:32,344 [mHTTP POST /add-funds 200 [0.04, 127.0.0.1:60239][0m
2024-09-09 06:13:40,007 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.02, 127.0.0.1:60239][0m
2024-09-09 06:13:40,008 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.02, 127.0.0.1:60274][0m
2024-09-09 06:13:43,565 [mHTTP POST /add-funds 200 [0.02, 127.0.0.1:60274][0m
2024-09-09 06:13:52,895 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.02, 127.0.0.1:60288][0m
2024-09-09 06:13:52,898 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.02, 127.0.0.1:60287][0m
2024-09-09 06:13:52,913 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.02, 127.0.0.1:60288][0m
2024-09-09 06:13:52,918 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.02, 127.0.0.1:60287][0m
2024-09-09 06:13:52,937 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.02, 127.0.0.1:60288][0m
2024-09-09 06:13:52,939 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.02, 127.0.0.1:60287][0m
2024-09-09 06:13:54,952 [mHTTP POST /add-funds 200 [0.02, 127.0.0.1:60287][0m
2024-09-09 06:13:57,316 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.01, 127.0.0.1:60288][0m
2024-09-09 06:13:57,316 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.01, 127.0.0.1:60287][0m
2024-09-09 06:13:57,333 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.01, 127.0.0.1:60287][0m
2024-09-09 06:13:57,333 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.01, 127.0.0.1:60288][0m
2024-09-09 06:13:57,551 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.03, 127.0.0.1:60288][0m
2024-09-09 06:13:57,551 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.03, 127.0.0.1:60287][0m
2024-09-09 06:14:00,415 [mHTTP POST /add-funds 200 [0.02, 127.0.0.1:60288][0m
2024-09-09 06:14:02,329 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.02, 127.0.0.1:60288][0m
2024-09-09 06:14:02,331 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.02, 127.0.0.1:60287][0m
2024-09-09 06:14:02,355 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.02, 127.0.0.1:60287][0m
2024-09-09 06:14:02,356 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.02, 127.0.0.1:60288][0m
2024-09-09 06:14:02,377 [33mHTTP GET /static/libs/bootstrap/dist/js/bootstrap.bundle.min.js.map 404 [0.02, 127.0.0.1:60287][0m
2024-09-09 06:14:02,378 [33mHTTP GET /static/libs/feather-icons/dist/feather.min.js.map 404 [0.02, 127.0.0.1:60288][0m
2024-09-09 06:14:32,366 [mHTTP GET /transactions 200 [0.04, 127.0.0.1:60288][0m
2024-09-09 06:14:47,657 [mHTTP GET /transactions 200 [0.05, 127.0.0.1:60288][0m
2024-09-09 06:17:42,385 D:\stox\app\urls.py changed, reloading.
2024-09-09 06:18:39,822 D:\stox\app\views.py changed, reloading.
2024-09-09 06:19:30,643 D:\stox\app\views.py changed, reloading.
2024-09-09 06:19:56,702 D:\stox\app\views.py changed, reloading.
2024-09-09 06:20:10,778 D:\stox\app\views.py changed, reloading.
2024-09-09 06:20:35,317 D:\stox\app\views.py changed, reloading.
2024-09-09 06:21:19,012 D:\stox\app\views.py changed, reloading.
2024-09-09 06:22:00,072 D:\stox\app\models.py changed, reloading.
2024-09-09 06:22:35,392 [mHTTP GET /transactions 200 [0.25, 127.0.0.1:60564][0m
2024-09-09 06:22:51,957 [mHTTP POST /add-funds 200 [0.46, 127.0.0.1:60572][0m
2024-09-09 06:30:23,612 Not Found: /payment-status/r2pc9HDdKX1DRR9
2024-09-09 06:30:23,615 [33mHTTP GET /payment-status/r2pc9HDdKX1DRR9?results=time%20out 404 [0.14, 127.0.0.1:60755][0m
2024-09-09 06:30:55,692 D:\stox\app\urls.py changed, reloading.
2024-09-09 06:31:00,156 [32mHTTP GET /payment-status/r2pc9HDdKX1DRR9?results=time%20out 302 [0.03, 127.0.0.1:60781][0m
2024-09-09 06:31:00,192 [mHTTP GET /transactions 200 [0.03, 127.0.0.1:60781][0m
2024-09-09 06:31:33,514 D:\stox\app\models.py changed, reloading.
2024-09-09 06:31:44,446 D:\stox\app\models.py changed, reloading.
2024-09-09 06:35:24,528 D:\stox\stock\settings.py changed, reloading.
2024-09-09 06:36:47,728 D:\stox\app\forms.py changed, reloading.
2024-09-09 06:38:05,601 Internal Server Error: /transactions
Traceback (most recent call last):
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: app_customuser.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
  File "C:\Program Files\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapper_view
    if test_func(request.user):
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 51, in <lambda>
    lambda u: u.is_authenticated,
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\utils\functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\middleware.py", line 33, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\middleware.py", line 13, in get_user
    request._cached_user = auth.get_user(request)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\__init__.py", line 216, in get_user
    user = backend.get_user(user_id)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\backends.py", line 157, in get_user
    user = UserModel._default_manager.get(pk=user_id)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: app_customuser.username
2024-09-09 06:38:05,611 [35;1mHTTP GET /transactions 500 [0.29, 127.0.0.1:60905][0m
2024-09-09 06:38:28,835 [mHTTP GET /transactions 200 [0.05, 127.0.0.1:60928][0m
2024-09-09 06:38:30,819 [mHTTP GET /profile 200 [0.02, 127.0.0.1:60928][0m
2024-09-09 06:38:33,289 [mHTTP GET /profile 200 [0.02, 127.0.0.1:60928][0m
2024-09-09 06:38:34,618 [mHTTP GET /profile 200 [0.02, 127.0.0.1:60928][0m
2024-09-09 06:38:36,755 [32mHTTP GET /logout 301 [0.02, 127.0.0.1:60928][0m
2024-09-09 06:38:36,774 [32mHTTP GET /logout/ 302 [0.01, 127.0.0.1:60928][0m
2024-09-09 06:38:36,801 [mHTTP GET /login/ 200 [0.02, 127.0.0.1:60928][0m
2024-09-09 06:38:37,080 [mHTTP GET /static/libs/simplebar/dist/simplebar.min.css 200 [0.22, 127.0.0.1:60928][0m
2024-09-09 06:38:47,872 Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
  File "C:\Program Files\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "D:\stox\app\views.py", line 86, in handlelogin
    user = authenticate(request, username=email, password=password)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\__init__.py", line 79, in authenticate
    user = backend.authenticate(request, **credentials)
  File "D:\stox\app\backends.py", line 9, in authenticate
    if '@' in username:
TypeError: argument of type 'NoneType' is not iterable
2024-09-09 06:38:47,880 [35;1mHTTP POST /login/ 500 [0.07, 127.0.0.1:60928][0m
2024-09-09 06:38:52,994 [mHTTP GET /login/ 200 [0.01, 127.0.0.1:60928][0m
2024-09-09 06:38:57,668 Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
  File "C:\Program Files\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "D:\stox\app\views.py", line 86, in handlelogin
    user = authenticate(request, username=email, password=password)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "C:\Users\atulg\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\__init__.py", line 79, in authenticate
    user = backend.authenticate(request, **credentials)
  File "D:\stox\app\backends.py", line 9, in authenticate
    if '@' in username:
TypeError: argument of type 'NoneType' is not iterable
2024-09-09 06:38:57,675 [35;1mHTTP POST /login/ 500 [0.04, 127.0.0.1:60928][0m
2024-09-09 06:39:54,994 D:\stox\app\views.py changed, reloading.
2024-09-09 06:39:58,138 [32mHTTP POST /login/ 302 [0.47, 127.0.0.1:60951][0m
2024-09-09 06:39:58,197 [mHTTP GET /watchlist?greeting=True 200 [0.06, 127.0.0.1:60951][0m
2024-09-09 06:40:00,674 [mHTTP GET /watchlist 200 [0.02, 127.0.0.1:60951][0m
2024-09-09 06:40:02,174 [mHTTP GET /admin/ 200 [0.13, 127.0.0.1:60951][0m
2024-09-09 06:40:06,739 [mHTTP GET /admin/app/customuser/ 200 [0.20, 127.0.0.1:60951][0m
2024-09-09 06:40:06,805 [mHTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:60951][0m
2024-09-09 06:40:06,824 [mHTTP GET /static/admin/img/icon-no.svg 200 [0.06, 127.0.0.1:60947][0m
2024-09-09 06:40:06,825 [mHTTP GET /static/admin/img/icon-yes.svg 200 [0.06, 127.0.0.1:60948][0m
2024-09-09 06:40:08,857 [mHTTP GET /admin/app/customuser/1/change/ 200 [0.21, 127.0.0.1:60948][0m
2024-09-09 06:40:08,897 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:60951][0m
2024-09-09 06:40:08,905 [mHTTP GET /static/admin/js/SelectBox.js 200 [0.02, 127.0.0.1:60948][0m
2024-09-09 06:40:08,906 [mHTTP GET /static/admin/js/SelectFilter2.js 200 [0.02, 127.0.0.1:60947][0m
2024-09-09 06:40:11,140 [mHTTP GET /admin/app/customuser/ 200 [0.05, 127.0.0.1:60948][0m
2024-09-09 06:40:42,820 D:\stox\app\admin.py changed, reloading.
2024-09-09 06:40:45,860 [mHTTP GET /admin/app/customuser/ 200 [0.12, 127.0.0.1:60971][0m
2024-09-09 06:40:45,897 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:60971][0m
2024-09-09 06:40:48,283 [mHTTP GET /admin/app/transaction/ 200 [0.08, 127.0.0.1:60971][0m
2024-09-09 06:40:48,313 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:60971][0m
2024-09-09 06:40:49,927 [mHTTP GET /admin/app/transaction/21/change/ 200 [0.09, 127.0.0.1:60971][0m
2024-09-09 06:40:49,961 [36mHTTP GET /static/admin/js/admin/DateTimeShortcuts.js 304 [0.00, 127.0.0.1:60965][0m
2024-09-09 06:40:49,961 [36mHTTP GET /static/admin/js/calendar.js 304 [0.01, 127.0.0.1:60966][0m
2024-09-09 06:40:49,973 [mHTTP GET /admin/jsi18n/ 200 [0.02, 127.0.0.1:60971][0m
2024-09-09 06:40:55,249 [mHTTP GET /admin/app/transaction/ 200 [0.17, 127.0.0.1:60971][0m
2024-09-09 06:42:02,388 D:\stox\app\admin.py changed, reloading.
2024-09-09 06:42:05,194 [mHTTP GET /admin/app/transaction/ 200 [0.14, 127.0.0.1:61010][0m
2024-09-09 06:42:05,230 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:61010][0m
2024-09-09 06:42:11,178 [mHTTP GET /admin/app/customuser/ 200 [0.05, 127.0.0.1:61010][0m
2024-09-09 06:42:11,234 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:61010][0m
2024-09-09 06:42:13,840 [mHTTP GET /admin/app/customuser/1/change/ 200 [0.10, 127.0.0.1:61010][0m
2024-09-09 06:42:13,976 [mHTTP GET /admin/jsi18n/ 200 [0.09, 127.0.0.1:61010][0m
2024-09-09 06:42:17,168 [32mHTTP POST /admin/app/customuser/1/change/ 302 [0.03, 127.0.0.1:61010][0m
2024-09-09 06:42:17,234 [mHTTP GET /admin/app/customuser/ 200 [0.06, 127.0.0.1:61010][0m
2024-09-09 06:42:17,270 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:61010][0m
2024-09-09 06:42:22,079 [mHTTP GET /admin/app/customuser/6/change/ 200 [0.10, 127.0.0.1:61010][0m
2024-09-09 06:42:22,113 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:61010][0m
2024-09-09 06:42:25,205 [32mHTTP POST /admin/app/customuser/6/change/ 302 [0.03, 127.0.0.1:61010][0m
2024-09-09 06:42:25,263 [mHTTP GET /admin/app/customuser/ 200 [0.05, 127.0.0.1:61010][0m
2024-09-09 06:42:25,306 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:61010][0m
2024-09-09 06:42:27,252 [mHTTP GET /admin/app/customuser/7/change/ 200 [0.08, 127.0.0.1:61010][0m
2024-09-09 06:42:27,284 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:61010][0m
2024-09-09 06:42:29,501 [32mHTTP POST /admin/app/customuser/7/change/ 302 [0.03, 127.0.0.1:61010][0m
2024-09-09 06:42:29,557 [mHTTP GET /admin/app/customuser/ 200 [0.05, 127.0.0.1:61010][0m
2024-09-09 06:42:29,593 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:61010][0m
2024-09-09 06:42:32,836 [mHTTP GET /profile 200 [0.01, 127.0.0.1:61010][0m
2024-09-09 06:42:34,858 [32mHTTP GET /logout/ 302 [0.02, 127.0.0.1:61010][0m
2024-09-09 06:42:34,873 [mHTTP GET /login/ 200 [0.01, 127.0.0.1:61010][0m
2024-09-09 06:42:41,823 [32mHTTP POST /login/ 302 [0.51, 127.0.0.1:61010][0m
2024-09-09 06:42:41,842 [mHTTP GET /watchlist?greeting=True 200 [0.01, 127.0.0.1:61010][0m
2024-09-09 06:42:49,959 [mHTTP GET /watchlist 200 [0.01, 127.0.0.1:61010][0m
2024-09-09 06:42:51,333 [mHTTP GET /profile 200 [0.01, 127.0.0.1:61010][0m
2024-09-09 06:42:53,955 [32mHTTP GET /logout/ 302 [0.02, 127.0.0.1:61010][0m
2024-09-09 06:42:53,968 [mHTTP GET /login/ 200 [0.01, 127.0.0.1:61010][0m
2024-09-09 06:42:56,256 [32mHTTP GET /signup 301 [0.02, 127.0.0.1:61010][0m
2024-09-09 06:42:56,312 [mHTTP GET /signup/ 200 [0.05, 127.0.0.1:61010][0m
2024-09-09 06:43:08,502 Forbidden (CSRF token from POST incorrect.): /admin/app/customuser/
2024-09-09 06:43:08,507 [31;1mHTTP POST /admin/app/customuser/ 403 [0.03, 127.0.0.1:61010][0m
2024-09-09 06:43:10,020 [32mHTTP GET /admin/app/customuser/ 302 [0.01, 127.0.0.1:61010][0m
2024-09-09 06:43:10,064 [mHTTP GET /admin/login/?next=/admin/app/customuser/ 200 [0.04, 127.0.0.1:61010][0m
2024-09-09 06:43:17,203 [32mHTTP POST /admin/login/?next=/admin/app/customuser/ 302 [0.54, 127.0.0.1:61010][0m
2024-09-09 06:43:17,258 [mHTTP GET /admin/app/customuser/ 200 [0.05, 127.0.0.1:61010][0m
2024-09-09 06:43:17,451 [mHTTP GET /admin/jsi18n/ 200 [0.11, 127.0.0.1:61010][0m
2024-09-09 06:43:24,678 [mHTTP POST /admin/app/customuser/ 200 [0.11, 127.0.0.1:61010][0m
2024-09-09 06:43:26,088 [32mHTTP POST /admin/app/customuser/ 302 [0.04, 127.0.0.1:61010][0m
2024-09-09 06:43:26,159 [mHTTP GET /admin/app/customuser/ 200 [0.07, 127.0.0.1:61010][0m
2024-09-09 06:43:26,192 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:61010][0m
2024-09-09 06:43:38,017 Forbidden (CSRF token from POST incorrect.): /signup/
2024-09-09 06:43:38,022 [31;1mHTTP POST /signup/ 403 [0.01, 127.0.0.1:61027][0m
2024-09-09 06:43:39,774 [32mHTTP GET /signup/ 302 [0.02, 127.0.0.1:61027][0m
2024-09-09 06:43:39,789 [32mHTTP GET /market 302 [0.01, 127.0.0.1:61027][0m
2024-09-09 06:43:39,810 [mHTTP GET /watchlist 200 [0.01, 127.0.0.1:61027][0m
2024-09-09 06:43:40,113 [mHTTP GET /watchlist 200 [0.01, 127.0.0.1:61027][0m
2024-09-09 06:43:42,685 [mHTTP GET /profile 200 [0.02, 127.0.0.1:61027][0m
2024-09-09 06:43:45,099 [32mHTTP GET /logout/ 302 [0.01, 127.0.0.1:61027][0m
2024-09-09 06:43:45,111 [mHTTP GET /login/ 200 [0.01, 127.0.0.1:61027][0m
2024-09-09 06:43:49,488 [mHTTP GET /signup/ 200 [0.01, 127.0.0.1:61027][0m
2024-09-09 06:44:08,599 [mHTTP POST /signup/ 200 [4.83, 127.0.0.1:61027][0m
2024-09-09 06:44:58,689 [32mHTTP GET /verify_user/E663TJGGlQGWTsrArX7cxh0v76K3heoBsPWR9gBMzggoZyj4se4rYH6AvM0l/ 302 [0.01, 127.0.0.1:61027][0m
2024-09-09 06:44:58,706 [mHTTP GET /login/ 200 [0.01, 127.0.0.1:61027][0m
2024-09-09 06:45:02,082 [32mHTTP GET /login 301 [0.03, 127.0.0.1:61027][0m
2024-09-09 06:45:02,098 [mHTTP GET /login/ 200 [0.01, 127.0.0.1:61027][0m
2024-09-09 06:45:14,922 [mHTTP POST /login/ 200 [0.49, 127.0.0.1:61027][0m
2024-09-09 06:45:21,793 [32mHTTP POST /login/ 302 [0.50, 127.0.0.1:61027][0m
2024-09-09 06:45:21,808 [mHTTP GET /watchlist?greeting=True 200 [0.01, 127.0.0.1:61027][0m
2024-09-09 06:45:24,832 [mHTTP GET /watchlist 200 [0.01, 127.0.0.1:61027][0m
2024-09-09 06:45:40,299 [32mHTTP GET /admin/app/customuser/ 302 [0.02, 127.0.0.1:61027][0m
2024-09-09 06:45:40,322 [mHTTP GET /admin/login/?next=/admin/app/customuser/ 200 [0.02, 127.0.0.1:61027][0m
2024-09-09 06:45:46,756 [32mHTTP POST /admin/login/?next=/admin/app/customuser/ 302 [0.51, 127.0.0.1:61027][0m
2024-09-09 06:45:46,806 [mHTTP GET /admin/app/customuser/ 200 [0.04, 127.0.0.1:61027][0m
2024-09-09 06:45:46,836 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:61027][0m
2024-09-09 06:46:25,345 [mHTTP GET /profile 200 [0.01, 127.0.0.1:61084][0m
2024-09-09 06:46:47,364 [mHTTP GET /profile 200 [0.03, 127.0.0.1:61084][0m
2024-09-09 06:46:57,119 [mHTTP GET /profile 200 [0.02, 127.0.0.1:61084][0m
2024-09-09 06:47:19,620 [mHTTP GET /profile 200 [0.03, 127.0.0.1:61084][0m
2024-09-09 06:47:44,912 [mHTTP GET /profile 200 [0.02, 127.0.0.1:61084][0m
2024-09-09 06:48:07,945 [mHTTP GET /profile 200 [0.02, 127.0.0.1:61084][0m
2024-09-09 06:48:18,167 [32mHTTP GET /market 302 [0.02, 127.0.0.1:61084][0m
2024-09-09 06:48:18,189 [mHTTP GET /watchlist 200 [0.02, 127.0.0.1:61084][0m
2024-09-09 06:48:21,391 [mHTTP GET /contact 200 [0.03, 127.0.0.1:61084][0m
2024-09-09 06:48:21,630 [mHTTP GET /static/landingasset/img/blog/4.jpg 200 [0.20, 127.0.0.1:61084][0m
2024-09-09 06:48:21,642 [mHTTP GET /static/landingasset/img/page-info-bg.png 200 [0.16, 127.0.0.1:61097][0m
2024-09-09 06:48:24,222 [mHTTP GET /profile 200 [0.01, 127.0.0.1:61097][0m
2024-09-09 06:49:05,385 D:\stox\app\views.py changed, reloading.
2024-09-09 06:49:20,120 D:\stox\stock\settings.py changed, reloading.
2024-09-09 06:49:22,940 [32mHTTP GET /market 302 [0.03, 127.0.0.1:61124][0m
2024-09-09 06:49:22,969 [mHTTP GET /watchlist 200 [0.02, 127.0.0.1:61124][0m
2024-09-09 06:49:28,854 [32mHTTP POST /create_watchlist 302 [0.01, 127.0.0.1:61124][0m
2024-09-09 06:49:28,874 [mHTTP GET /watchlist 200 [0.02, 127.0.0.1:61124][0m
2024-09-09 06:50:19,514 D:\stox\app\views.py changed, reloading.
2024-09-09 06:50:22,099 [mHTTP GET /watchlist 200 [0.04, 127.0.0.1:61153][0m
2024-09-09 06:50:26,189 [32mHTTP POST /create_watchlist 302 [0.01, 127.0.0.1:61161][0m
2024-09-09 06:50:26,208 [mHTTP GET /watchlist 200 [0.01, 127.0.0.1:61161][0m
2024-09-09 06:51:07,000 D:\stox\app\views.py changed, reloading.
2024-09-09 06:51:09,539 [mHTTP GET /watchlist 200 [0.04, 127.0.0.1:61175][0m
2024-09-09 06:51:13,674 [32mHTTP POST /create_watchlist 302 [0.01, 127.0.0.1:61175][0m
2024-09-09 06:51:13,692 [mHTTP GET /watchlist 200 [0.01, 127.0.0.1:61175][0m
2024-09-09 06:53:11,511 [mHTTP GET /watchlist 200 [0.05, 127.0.0.1:61194][0m
2024-09-09 06:53:15,287 [32mHTTP POST /create_watchlist 302 [0.02, 127.0.0.1:61194][0m
2024-09-09 06:53:15,306 [mHTTP GET /watchlist 200 [0.02, 127.0.0.1:61194][0m
2024-09-09 06:54:32,549 [mHTTP GET /search/?q=sbin 200 [0.09, 127.0.0.1:61207][0m
2024-09-09 06:55:31,269 [mHTTP GET /watchlist 200 [0.04, 127.0.0.1:61207][0m
2024-09-09 06:55:45,437 D:\stox\app\admin.py changed, reloading.
2024-09-09 06:56:16,089 [mHTTP GET /admin/app/customuser/ 200 [0.13, 127.0.0.1:61262][0m
2024-09-09 06:56:16,162 [mHTTP GET /admin/jsi18n/ 200 [0.02, 127.0.0.1:61262][0m
2024-09-09 06:56:19,616 [mHTTP GET /admin/app/tags/ 200 [0.04, 127.0.0.1:61262][0m
2024-09-09 06:56:19,645 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:61262][0m
2024-09-09 06:56:24,695 [mHTTP POST /admin/app/tags/ 200 [0.07, 127.0.0.1:61262][0m
2024-09-09 06:56:26,731 [32mHTTP POST /admin/app/tags/ 302 [0.04, 127.0.0.1:61262][0m
2024-09-09 06:56:26,805 [mHTTP GET /admin/app/tags/ 200 [0.06, 127.0.0.1:61262][0m
2024-09-09 06:56:26,843 [mHTTP GET /admin/jsi18n/ 200 [0.01, 127.0.0.1:61262][0m
2024-09-09 06:56:29,278 [mHTTP GET /watchlist 200 [0.02, 127.0.0.1:61262][0m
2024-09-09 06:57:53,574 D:\stox\stock\settings.py changed, reloading.
